runname: testrun

# 1. samples file
sample_file: sample_list.txt

# 2. programs, references, etc.
atlas: /home/guido_gnecchi/cluster_home_backup_210810/atlas/atlas
ref: /mnt/archgen/Reference_Genomes/Human/hs37d5/hs37d5.fa
alleles: /mnt/archgen/HistoGenes/analysis/ATLAS/1KGP.atlas.alleles

# 3. general atlas parameters applying to all jobs unless specified within the job parameters.
#    these are examples, recommended for human ancient DNA data analysis.

#chromosomes for which ATLAS will run
atlasParams: "chr=1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,X,Y filterSoftClips"


# 4. specific parameters for Atlas-task splitMerge
splitMergeParams: ""


# 5. recalibration parameters:
# 5.1. specify the path to a bedfile containing the recalibration regions (e.g. UCNE)
recalInput: /mnt/archgen/users/gnecchi/Jena/HISTOGENES/analysis/88_mammals.epo_low_coverage.10M_GRCh37.masked.bed

# 5.2. specify if recalInput is containing regions or windows (can be "regions" or "windows")
recalFormat: regions

# 5.3. specific parameters for Atlas-task recal
recalParams: ""

# 6. should post-mortem damage (PMD) be calculated? (T or F)
PMD: T
pmdParams: ""

# 7. should a new BAMfile be produced with updated base quality scores based on PMD and recal estimation? (T or F)
recalBAM: T
recalBamParams: ""
